# Generated by Django 2.1.3 on 2018-11-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word2Vec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=64, verbose_name='单词')),
                ('vec', models.TextField(default='', verbose_name='词向量')),
            ],
        ),
    ]
